Rktraz master test
logicalclocks/hopsworks-tutorials pull request #100
Opened 2022-10-05 19:52 UTC by rktraz

2022-10-06 18:22 UTC, Maxxx-zh commented
⚠️ Problem with **td_transformation_functions** retrieval.

<img width="1106" alt="Знімок екрана 2022-10-06 о 9 21 17 пп" src="https://user-images.githubusercontent.com/63515947/194389635-84f04446-bc00-4ea7-b73e-a5f4618d0857.png">
<img width="1056" alt="Знімок екрана 2022-10-06 о 9 21 26 пп" src="https://user-images.githubusercontent.com/63515947/194389648-36c09ee3-81b0-44a9-838e-63d2fbdf6aec.png">

2022-10-09 19:10 UTC, davitbzh requested changes

2022-10-09 19:10 UTC, davitbzh commented on advanced_tutorials/electricity/README.md
> +
Write about feature views and point to docs. TD in created from FV not FG

2022-10-09 19:10 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/1_backfill_feature_groups.ipynb
> +    "1. **Load some data from files**,\n",
avoid word "some". Write just "load data from source files"

2022-10-09 19:10 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/1_backfill_feature_groups.ipynb
> +    "1. **Load some data from files**,\n",
avoid word "some". Write just "load data from source files"

2022-10-09 19:10 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/2_feature_pipeline.ipynb
> +    "2. **Insertion new data into Feature Store**."
Insert new data into the Feature Store

2022-10-09 19:10 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/2_feature_pipeline.ipynb
> +    "2. **Insertion new data into Feature Store**."
Insert new data into the Feature Store

2022-10-09 19:11 UTC, davitbzh commented
Also please remove cached files

2022-10-14 15:01 UTC, rktraz commented
wait a lil bit, I want to improve streamlit + `get_train_test_split` returns in new style

2022-10-17 09:02 UTC, davitbzh requested changes

2022-10-17 09:02 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/README.md
> +4. How to train a model and upload it to the Model Registry,
remove "How to "

2022-10-17 09:02 UTC, davitbzh commented on advanced_tutorials/nyc_taxi_fares/README.md
> +5. Streamlit app.
Deploy streamlit app

2022-10-17 11:43 UTC, rktraz commented on advanced_tutorials/electricity/1_backfill_feature_groups.ipynb
> +    "1. **Loading the data and feature engineeing**,\n",
Davit, why don't you like such constructions like _"Loading, modeling..."_?

It s used in many tutorials on the internet
And in the sentence _"Loading the data and feature engineering"_  there is a _"feature engineering"_ part that is strange to change to "engineer features"

2022-10-17 11:46 UTC, rktraz commented on advanced_tutorials/electricity/README.md
> +
I think it is comfortable when we have fundamental questions that our project is divided into, and in each part, we answer one of these questions

So should I write
`
...
3. Create Feature views & Training Datasets,
4. Train a model and upload it to the Model Registry,
5. Fetch the model from Model Registry and make batch predictions...
`

?

2022-10-19 09:05 UTC, davitbzh approved these changes

2022-10-19 09:07 UTC, merged