[FSTORE-850] DBT tutorial with BigQuery
logicalclocks/hopsworks-tutorials pull request #166
Opened 2023-05-09 18:38 UTC by Maxxx-zh

2023-05-10 07:00 UTC, jimdowling commented
Can you rename the directory from 'dbt' to 'dbt_bq' ?

2023-05-10 07:07 UTC, jimdowling commented
Is it possible to set the hopsworks ENV variables in the dbt_project.yml file?
 HOPSWORKS_PROJECT, HOPSWORKS_HOST
 What about HOPSWORKS_API_KEY - where should that be set?

2023-05-10 20:35 UTC, Maxxx-zh commented
> Did you try inserting a PySpark dataframe into Hopsworks, instead of a Pandas DF - which is much slower?

Got the next error:
`typeerror: The provided dataframe type is not recognized. Supported types are: pandas dataframe. The provided dataframe has type: <class 'pyspark.sql.dataframe.DataFrame'>`

2023-05-10 20:38 UTC, Maxxx-zh commented
> Is it possible to set the hopsworks ENV variables in the dbt_project.yml file?
> HOPSWORKS_PROJECT, HOPSWORKS_HOST
> What about HOPSWORKS_API_KEY - where should that be set?

<img width="908" alt="Знімок екрана 2023-05-10 о 23 34 42" src="https://github.com/logicalclocks/hopsworks-tutorials/assets/63515947/637b6b9f-537c-4caa-aade-0868c792c315">

2023-05-20 11:49 UTC, jimdowling approved these changes
Fixes in the readme

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +
This tutorial shows you how to perform feature engineering in DBT on BigQuery, storing offline computed features in a table in BigQuery (that is mounted as an external feature group in Hopsworks) and online features in Hopsworks. The online features are written to Hopsworks using a Python module that is run on a DataProc cluster. The feature group created in Hopsworks has its offline data stored in BigQuery and its online data stored in Hopsworks online store (RonDB).

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +You need to configure an external Spark cluster to be able to interact with the Hopsworks Feature Store.
First, you need to setup a Dataproc (Spark) cluster that will run the Python model in our DBT workflow. The Python model will write to the online feature store in Hopsworks.

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +Code to create Dataproc cluster is present in `provision.sh` file.
You can find the code to create the Dataproc cluster in `provision.sh`.

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +To make `provision.sh` file executable do the next:
executable, run the following command:

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +Fill in your cluster information and then use `./provision.sh` command to start the cluster creation.
then run the `./provision.sh` command

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +Install the BigQuery adapter running
by running

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +{YOUR_PROJECT_NAME}:
YOUR_GCP_PROJECT_NAME
or 
YOUR_HOPSWORKS_PROJECT_NAME
or
YOUR_DBT_PROJECT_NAME

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +     project: [your-project-id]
your-gcp-project-id

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +     # Your Google Cloud project name
it's the project id, not the project name, right?

2023-05-20 11:49 UTC, jimdowling commented on integrations/dbt_bq/README.md
> +Fill in `read_bigquery_data.sql` and `data_pipeline.py` files with your information.
with your feature engineering code that creates features and writes them to the BQ offline table and Hopsworks online table.

2023-05-20 11:49 UTC, jimdowling approved these changes
Fixes in the readme

2023-05-23 08:41 UTC, davitbzh requested changes

2023-05-23 08:41 UTC, davitbzh commented on integrations/dbt_bq/provision.sh
> +    --optional-components JUPYTER \
This is not needed

2023-05-23 12:38 UTC, davitbzh approved these changes

2023-05-23 12:39 UTC, merged