[FSTORE-798][APPEND] Clean up beam pom.xml
logicalclocks/hopsworks-tutorials pull request #172
Opened 2023-06-05 21:31 UTC by davitbzh

2023-07-31 15:58 UTC, kennethmhc commented on integrations/java/beam/README.md
> +service account has the Pub/Sub Subscriber role.
I think it needs to be `Pub/Sub Admin`

2023-07-31 16:01 UTC, davitbzh commented on integrations/java/beam/README.md
> +service account has the Pub/Sub Subscriber role.
done

2023-08-01 08:42 UTC, kennethmhc requested changes

2023-08-01 08:42 UTC, kennethmhc commented on integrations/java/flink/pom.xml
> +    <version>3.4.0-SNAPSHOT</version>
`<flink.version>1.17.0.0</flink.version>` this should be `1.17.0`

2023-08-03 09:34 UTC, kennethmhc approved these changes
LGTM!

2023-08-03 09:42 UTC, kennethmhc approved these changes

2023-08-03 09:45 UTC, Maxxx-zh approved these changes

2023-08-03 09:46 UTC, merged